"use client";

import { useEffect, useState } from "react";
import { ROLES } from "@/domain/roles";

type User = { id: string; fullName: string; email: string; role: string; status: string; managerId: string | null };
type ApiPayload = { users?: User[]; user?: User; error?: { message: string } };
type NewUser = { fullName: string; email: string; password: string; role: string; status: string; managerId: string };

export function ManageUsersPanel() {
  const [users, setUsers] = useState<User[]>([]);
  const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [isIt, setIsIt] = useState(false);
  const [newUser, setNewUser] = useState<NewUser>({ fullName: "", email: "", password: "password123", role: ROLES.USER, status: "active", managerId: "" });
  async function load() { const [usersResponse, meResponse] = await Promise.all([fetch("/api/users", { cache: "no-store" }), fetch("/api/auth/me", { cache: "no-store" })]); const payload: ApiPayload = await usersResponse.json(); const me: ApiPayload = await meResponse.json(); if (!usersResponse.ok) { setError(payload.error?.message ?? "Could not load users."); return; } setUsers(payload.users ?? []); setIsIt(me.user?.role === ROLES.IT); }
  useEffect(() => { void load(); }, []);
  async function update(id: string, body: Record<string, string>, success: string) { setError(""); setMessage(""); const endpoint = body.role ? "role" : body.status ? "status" : "profile"; const response = await fetch(`/api/users/${id}/${endpoint}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const payload: ApiPayload = await response.json(); if (!response.ok) { setError(payload.error?.message ?? "Update failed."); return; } setMessage(success); await load(); }
  async function create(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setError(""); setMessage(""); const response = await fetch("/api/users", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...newUser, managerId: newUser.managerId || null }) }); const payload: ApiPayload = await response.json(); if (!response.ok) { setError(payload.error?.message ?? "Create failed."); return; } setMessage("User created."); setNewUser({ fullName: "", email: "", password: "password123", role: ROLES.USER, status: "active", managerId: "" }); await load(); }
  return <>{error && <p className="error">{error}</p>}{message && <p className="success">{message}</p>}{isIt && <form className="panel grid" onSubmit={create}><h2>Create user</h2><label>Full name<input value={newUser.fullName} onChange={(e) => setNewUser({ ...newUser, fullName: e.target.value })} required /></label><label>Email<input type="email" value={newUser.email} onChange={(e) => setNewUser({ ...newUser, email: e.target.value })} required /></label><label>Password<input value={newUser.password} onChange={(e) => setNewUser({ ...newUser, password: e.target.value })} required /></label><label>Role<select value={newUser.role} onChange={(e) => setNewUser({ ...newUser, role: e.target.value })}><option value={ROLES.USER}>{ROLES.USER}</option><option value={ROLES.MANAGER}>{ROLES.MANAGER}</option><option value={ROLES.IT}>{ROLES.IT}</option></select></label><label>Manager ID<input value={newUser.managerId} onChange={(e) => setNewUser({ ...newUser, managerId: e.target.value })} placeholder="optional" /></label><button type="submit">Create</button></form>}<div className="panel"><p>{users.length} users visible.</p><table><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Status</th><th>Actions</th></tr></thead><tbody>{users.map((user) => <UserRow key={user.id} user={user} isIt={isIt} update={update} />)}</tbody></table></div></>;
}

function UserRow({ user, isIt, update }: { user: User; isIt: boolean; update: (id: string, body: Record<string, string>, success: string) => Promise<void> }) { const [name, setName] = useState(user.fullName); const [email, setEmail] = useState(user.email); return <tr><td><input value={name} onChange={(e) => setName(e.target.value)} /></td><td><input value={email} onChange={(e) => setEmail(e.target.value)} /></td><td>{isIt ? <select value={user.role} onChange={(e) => void update(user.id, { role: e.target.value }, "Role updated.")}><option value={ROLES.IT}>{ROLES.IT}</option><option value={ROLES.MANAGER}>{ROLES.MANAGER}</option><option value={ROLES.USER}>{ROLES.USER}</option></select> : user.role}</td><td>{isIt ? <button className={user.status === "active" ? "danger" : "secondary"} onClick={() => void update(user.id, { status: user.status === "active" ? "deactivated" : "active" }, "Status updated.")}>{user.status === "active" ? "Deactivate" : "Activate"}</button> : user.status}</td><td><button onClick={() => void update(user.id, { fullName: name, email }, "Profile updated.")}>Save profile</button></td></tr>; }
